//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comdat.DOZP.Process.DozpService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class DozpServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchRequest", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class SearchRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CatalogueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CatalogueID {
            get {
                return this.CatalogueIDField;
            }
            set {
                if ((this.CatalogueIDField.Equals(value) != true)) {
                    this.CatalogueIDField = value;
                    this.RaisePropertyChanged("CatalogueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SysNo {
            get {
                return this.SysNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SysNoField, value) != true)) {
                    this.SysNoField = value;
                    this.RaisePropertyChanged("SysNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObalkyKnihRequest", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class ObalkyKnihRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comdat.DOZP.Process.DozpService.ObalkyKnihBibInfo bibinfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string permalinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zserverUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comdat.DOZP.Process.DozpService.ObalkyKnihBibInfo bibinfo {
            get {
                return this.bibinfoField;
            }
            set {
                if ((object.ReferenceEquals(this.bibinfoField, value) != true)) {
                    this.bibinfoField = value;
                    this.RaisePropertyChanged("bibinfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string permalink {
            get {
                return this.permalinkField;
            }
            set {
                if ((object.ReferenceEquals(this.permalinkField, value) != true)) {
                    this.permalinkField = value;
                    this.RaisePropertyChanged("permalink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zserverUrl {
            get {
                return this.zserverUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.zserverUrlField, value) != true)) {
                    this.zserverUrlField = value;
                    this.RaisePropertyChanged("zserverUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObalkyKnihBibInfo", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class ObalkyKnihBibInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> authorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string issnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oclcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sysnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> authors {
            get {
                return this.authorsField;
            }
            set {
                if ((object.ReferenceEquals(this.authorsField, value) != true)) {
                    this.authorsField = value;
                    this.RaisePropertyChanged("authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ean {
            get {
                return this.eanField;
            }
            set {
                if ((object.ReferenceEquals(this.eanField, value) != true)) {
                    this.eanField = value;
                    this.RaisePropertyChanged("ean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string issn {
            get {
                return this.issnField;
            }
            set {
                if ((object.ReferenceEquals(this.issnField, value) != true)) {
                    this.issnField = value;
                    this.RaisePropertyChanged("issn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nbn {
            get {
                return this.nbnField;
            }
            set {
                if ((object.ReferenceEquals(this.nbnField, value) != true)) {
                    this.nbnField = value;
                    this.RaisePropertyChanged("nbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oclc {
            get {
                return this.oclcField;
            }
            set {
                if ((object.ReferenceEquals(this.oclcField, value) != true)) {
                    this.oclcField = value;
                    this.RaisePropertyChanged("oclc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sysno {
            get {
                return this.sysnoField;
            }
            set {
                if ((object.ReferenceEquals(this.sysnoField, value) != true)) {
                    this.sysnoField = value;
                    this.RaisePropertyChanged("sysno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string year {
            get {
                return this.yearField;
            }
            set {
                if ((object.ReferenceEquals(this.yearField, value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObalkyKnihResponse", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.Institution))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Comdat.DOZP.Core.Catalogue>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.Catalogue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.Report))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.Book))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Comdat.DOZP.Core.ScanFile>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.ScanFile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.PartOfBook))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.StatusCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.BookFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.DateRange))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.DateRange.DateType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Comdat.DOZP.Core.Book>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Core.ScanFileFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.SearchRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.ObalkyKnihRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.ObalkyKnihBibInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.ScanFileRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.ScanImageResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.ScanImageRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.ScanFileResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.OcrFileRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Comdat.DOZP.Process.DozpService.OcrFileResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    public partial class ObalkyKnihResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string backlink_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comdat.DOZP.Process.DozpService.ObalkyKnihBibInfo bibinfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bookidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cover_icon_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] cover_imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cover_medium_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cover_thumbnail_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oclcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rating_countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rating_sumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<object> reviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toc_pdf_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toc_text_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toc_thumbnail_urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _id {
            get {
                return this._idField;
            }
            set {
                if ((object.ReferenceEquals(this._idField, value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string backlink_url {
            get {
                return this.backlink_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.backlink_urlField, value) != true)) {
                    this.backlink_urlField = value;
                    this.RaisePropertyChanged("backlink_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comdat.DOZP.Process.DozpService.ObalkyKnihBibInfo bibinfo {
            get {
                return this.bibinfoField;
            }
            set {
                if ((object.ReferenceEquals(this.bibinfoField, value) != true)) {
                    this.bibinfoField = value;
                    this.RaisePropertyChanged("bibinfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookid {
            get {
                return this.bookidField;
            }
            set {
                if ((object.ReferenceEquals(this.bookidField, value) != true)) {
                    this.bookidField = value;
                    this.RaisePropertyChanged("bookid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cover_icon_url {
            get {
                return this.cover_icon_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.cover_icon_urlField, value) != true)) {
                    this.cover_icon_urlField = value;
                    this.RaisePropertyChanged("cover_icon_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] cover_image {
            get {
                return this.cover_imageField;
            }
            set {
                if ((object.ReferenceEquals(this.cover_imageField, value) != true)) {
                    this.cover_imageField = value;
                    this.RaisePropertyChanged("cover_image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cover_medium_url {
            get {
                return this.cover_medium_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.cover_medium_urlField, value) != true)) {
                    this.cover_medium_urlField = value;
                    this.RaisePropertyChanged("cover_medium_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cover_thumbnail_url {
            get {
                return this.cover_thumbnail_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.cover_thumbnail_urlField, value) != true)) {
                    this.cover_thumbnail_urlField = value;
                    this.RaisePropertyChanged("cover_thumbnail_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ean {
            get {
                return this.eanField;
            }
            set {
                if ((object.ReferenceEquals(this.eanField, value) != true)) {
                    this.eanField = value;
                    this.RaisePropertyChanged("ean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nbn {
            get {
                return this.nbnField;
            }
            set {
                if ((object.ReferenceEquals(this.nbnField, value) != true)) {
                    this.nbnField = value;
                    this.RaisePropertyChanged("nbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oclc {
            get {
                return this.oclcField;
            }
            set {
                if ((object.ReferenceEquals(this.oclcField, value) != true)) {
                    this.oclcField = value;
                    this.RaisePropertyChanged("oclc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rating_count {
            get {
                return this.rating_countField;
            }
            set {
                if ((this.rating_countField.Equals(value) != true)) {
                    this.rating_countField = value;
                    this.RaisePropertyChanged("rating_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rating_sum {
            get {
                return this.rating_sumField;
            }
            set {
                if ((this.rating_sumField.Equals(value) != true)) {
                    this.rating_sumField = value;
                    this.RaisePropertyChanged("rating_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<object> reviews {
            get {
                return this.reviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewsField, value) != true)) {
                    this.reviewsField = value;
                    this.RaisePropertyChanged("reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string toc_pdf_url {
            get {
                return this.toc_pdf_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.toc_pdf_urlField, value) != true)) {
                    this.toc_pdf_urlField = value;
                    this.RaisePropertyChanged("toc_pdf_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string toc_text_url {
            get {
                return this.toc_text_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.toc_text_urlField, value) != true)) {
                    this.toc_text_urlField = value;
                    this.RaisePropertyChanged("toc_text_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string toc_thumbnail_url {
            get {
                return this.toc_thumbnail_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.toc_thumbnail_urlField, value) != true)) {
                    this.toc_thumbnail_urlField = value;
                    this.RaisePropertyChanged("toc_thumbnail_url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanFileRequest", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class ScanFileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComputerField;
        
        private int ScanFileIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Computer {
            get {
                return this.ComputerField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputerField, value) != true)) {
                    this.ComputerField = value;
                    this.RaisePropertyChanged("Computer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScanFileID {
            get {
                return this.ScanFileIDField;
            }
            set {
                if ((this.ScanFileIDField.Equals(value) != true)) {
                    this.ScanFileIDField = value;
                    this.RaisePropertyChanged("ScanFileID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanImageResponse", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class ScanImageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        private int ScanFileIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScanFileID {
            get {
                return this.ScanFileIDField;
            }
            set {
                if ((this.ScanFileIDField.Equals(value) != true)) {
                    this.ScanFileIDField = value;
                    this.RaisePropertyChanged("ScanFileID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanImageRequest", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class ScanImageRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComputerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ObalkyKnihCZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comdat.DOZP.Core.PartOfBook PartOfBookField;
        
        private int ScanFileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseOCRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BookID {
            get {
                return this.BookIDField;
            }
            set {
                if ((this.BookIDField.Equals(value) != true)) {
                    this.BookIDField = value;
                    this.RaisePropertyChanged("BookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Computer {
            get {
                return this.ComputerField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputerField, value) != true)) {
                    this.ComputerField = value;
                    this.RaisePropertyChanged("Computer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ObalkyKnihCZ {
            get {
                return this.ObalkyKnihCZField;
            }
            set {
                if ((this.ObalkyKnihCZField.Equals(value) != true)) {
                    this.ObalkyKnihCZField = value;
                    this.RaisePropertyChanged("ObalkyKnihCZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comdat.DOZP.Core.PartOfBook PartOfBook {
            get {
                return this.PartOfBookField;
            }
            set {
                if ((this.PartOfBookField.Equals(value) != true)) {
                    this.PartOfBookField = value;
                    this.RaisePropertyChanged("PartOfBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScanFileID {
            get {
                return this.ScanFileIDField;
            }
            set {
                if ((this.ScanFileIDField.Equals(value) != true)) {
                    this.ScanFileIDField = value;
                    this.RaisePropertyChanged("ScanFileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseOCR {
            get {
                return this.UseOCRField;
            }
            set {
                if ((this.UseOCRField.Equals(value) != true)) {
                    this.UseOCRField = value;
                    this.RaisePropertyChanged("UseOCR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanFileResponse", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class ScanFileResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        private int ScanFileIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScanFileID {
            get {
                return this.ScanFileIDField;
            }
            set {
                if ((this.ScanFileIDField.Equals(value) != true)) {
                    this.ScanFileIDField = value;
                    this.RaisePropertyChanged("ScanFileID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OcrFileRequest", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class OcrFileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComputerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OcrTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PdfFileField;
        
        private int ScanFileIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Computer {
            get {
                return this.ComputerField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputerField, value) != true)) {
                    this.ComputerField = value;
                    this.RaisePropertyChanged("Computer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OcrText {
            get {
                return this.OcrTextField;
            }
            set {
                if ((object.ReferenceEquals(this.OcrTextField, value) != true)) {
                    this.OcrTextField = value;
                    this.RaisePropertyChanged("OcrText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PdfFile {
            get {
                return this.PdfFileField;
            }
            set {
                if ((object.ReferenceEquals(this.PdfFileField, value) != true)) {
                    this.PdfFileField = value;
                    this.RaisePropertyChanged("PdfFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScanFileID {
            get {
                return this.ScanFileIDField;
            }
            set {
                if ((this.ScanFileIDField.Equals(value) != true)) {
                    this.ScanFileIDField = value;
                    this.RaisePropertyChanged("ScanFileID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OcrFileResponse", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
    [System.SerializableAttribute()]
    public partial class OcrFileResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        private int ScanFileIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScanFileID {
            get {
                return this.ScanFileIDField;
            }
            set {
                if ((this.ScanFileIDField.Equals(value) != true)) {
                    this.ScanFileIDField = value;
                    this.RaisePropertyChanged("ScanFileID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ffas04.ff.cuni.cz//2015/01", ConfigurationName="DozpService.DozpService")]
    public interface DozpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/ServiceInfo", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/ServiceInfoResponse")]
        string ServiceInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/Authenticate", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/AuthenticateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/AuthenticateDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Core.User Authenticate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetInstitution", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetInstitutionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetInstitutionDozpServiceFaultFault" +
            "", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Core.Institution GetInstitution();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/SearchBook", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/SearchBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/SearchBookDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Core.Report SearchBook(Comdat.DOZP.Process.DozpService.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/SearchObalkyKnihCZ", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/SearchObalkyKnihCZResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/SearchObalkyKnihCZDozpServiceFaultF" +
            "ault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Process.DozpService.ObalkyKnihResponse SearchObalkyKnihCZ(Comdat.DOZP.Process.DozpService.ObalkyKnihRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetBook", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetBookDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Core.Book GetBook(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetBooks", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetBooksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetBooksDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        System.Collections.Generic.List<Comdat.DOZP.Core.Book> GetBooks(Comdat.DOZP.Core.BookFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/SaveBook", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/SaveBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/SaveBookDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Core.Book SaveBook(Comdat.DOZP.Core.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/DeleteBook", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/DeleteBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/DeleteBookDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        bool DeleteBook(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetScanFiles", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetScanFilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetScanFilesDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        System.Collections.Generic.List<Comdat.DOZP.Core.ScanFile> GetScanFiles(Comdat.DOZP.Core.ScanFileFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetScanImage", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetScanImageResponse")]
        Comdat.DOZP.Process.DozpService.ScanImageResponse GetScanImage(Comdat.DOZP.Process.DozpService.ScanFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetContentsToOCR", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetContentsToOCRResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/GetContentsToOCRDozpServiceFaultFau" +
            "lt", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Core.ScanFile GetContentsToOCR();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/SaveScanImage", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/SaveScanImageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/SaveScanImageDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Process.DozpService.ScanFileResponse SaveScanImage(Comdat.DOZP.Process.DozpService.ScanImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/CheckOutContents", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/CheckOutContentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/CheckOutContentsDozpServiceFaultFau" +
            "lt", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Process.DozpService.ScanImageResponse CheckOutContents(Comdat.DOZP.Process.DozpService.ScanFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/CheckInContents", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/CheckInContentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/CheckInContentsDozpServiceFaultFaul" +
            "t", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Process.DozpService.OcrFileResponse CheckInContents(Comdat.DOZP.Process.DozpService.OcrFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/DiscardContents", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/DiscardContentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/DiscardContentsDozpServiceFaultFaul" +
            "t", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Process.DozpService.ScanFileResponse DiscardContents(Comdat.DOZP.Process.DozpService.ScanFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/CancelOcrContents", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/CancelOcrContentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/CancelOcrContentsDozpServiceFaultFa" +
            "ult", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Process.DozpService.ScanFileResponse CancelOcrContents(Comdat.DOZP.Process.DozpService.ScanFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/UndoContents", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/UndoContentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/UndoContentsDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Process.DozpService.ScanFileResponse UndoContents(Comdat.DOZP.Process.DozpService.ScanFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/DeleteScanFile", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/DeleteScanFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/DeleteScanFileDozpServiceFaultFault" +
            "", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        Comdat.DOZP.Process.DozpService.ScanFileResponse DeleteScanFile(Comdat.DOZP.Process.DozpService.ScanFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/LogError", ReplyAction="http://ffas04.ff.cuni.cz//2015/01/DozpService/LogErrorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Comdat.DOZP.Process.DozpService.DozpServiceFault), Action="http://ffas04.ff.cuni.cz//2015/01/DozpService/LogErrorDozpServiceFaultFault", Name="DozpServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Comdat.DOZP.Services")]
        bool LogError(string application, string machineName, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DozpServiceChannel : Comdat.DOZP.Process.DozpService.DozpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DozpServiceClient : System.ServiceModel.ClientBase<Comdat.DOZP.Process.DozpService.DozpService>, Comdat.DOZP.Process.DozpService.DozpService {
        
        public DozpServiceClient() {
        }
        
        public DozpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DozpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DozpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DozpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServiceInfo() {
            return base.Channel.ServiceInfo();
        }
        
        public Comdat.DOZP.Core.User Authenticate() {
            return base.Channel.Authenticate();
        }
        
        public Comdat.DOZP.Core.Institution GetInstitution() {
            return base.Channel.GetInstitution();
        }
        
        public Comdat.DOZP.Core.Report SearchBook(Comdat.DOZP.Process.DozpService.SearchRequest request) {
            return base.Channel.SearchBook(request);
        }
        
        public Comdat.DOZP.Process.DozpService.ObalkyKnihResponse SearchObalkyKnihCZ(Comdat.DOZP.Process.DozpService.ObalkyKnihRequest request) {
            return base.Channel.SearchObalkyKnihCZ(request);
        }
        
        public Comdat.DOZP.Core.Book GetBook(int bookID) {
            return base.Channel.GetBook(bookID);
        }
        
        public System.Collections.Generic.List<Comdat.DOZP.Core.Book> GetBooks(Comdat.DOZP.Core.BookFilter filter) {
            return base.Channel.GetBooks(filter);
        }
        
        public Comdat.DOZP.Core.Book SaveBook(Comdat.DOZP.Core.Book book) {
            return base.Channel.SaveBook(book);
        }
        
        public bool DeleteBook(int bookID) {
            return base.Channel.DeleteBook(bookID);
        }
        
        public System.Collections.Generic.List<Comdat.DOZP.Core.ScanFile> GetScanFiles(Comdat.DOZP.Core.ScanFileFilter filter) {
            return base.Channel.GetScanFiles(filter);
        }
        
        public Comdat.DOZP.Process.DozpService.ScanImageResponse GetScanImage(Comdat.DOZP.Process.DozpService.ScanFileRequest request) {
            return base.Channel.GetScanImage(request);
        }
        
        public Comdat.DOZP.Core.ScanFile GetContentsToOCR() {
            return base.Channel.GetContentsToOCR();
        }
        
        public Comdat.DOZP.Process.DozpService.ScanFileResponse SaveScanImage(Comdat.DOZP.Process.DozpService.ScanImageRequest request) {
            return base.Channel.SaveScanImage(request);
        }
        
        public Comdat.DOZP.Process.DozpService.ScanImageResponse CheckOutContents(Comdat.DOZP.Process.DozpService.ScanFileRequest request) {
            return base.Channel.CheckOutContents(request);
        }
        
        public Comdat.DOZP.Process.DozpService.OcrFileResponse CheckInContents(Comdat.DOZP.Process.DozpService.OcrFileRequest request) {
            return base.Channel.CheckInContents(request);
        }
        
        public Comdat.DOZP.Process.DozpService.ScanFileResponse DiscardContents(Comdat.DOZP.Process.DozpService.ScanFileRequest request) {
            return base.Channel.DiscardContents(request);
        }
        
        public Comdat.DOZP.Process.DozpService.ScanFileResponse CancelOcrContents(Comdat.DOZP.Process.DozpService.ScanFileRequest request) {
            return base.Channel.CancelOcrContents(request);
        }
        
        public Comdat.DOZP.Process.DozpService.ScanFileResponse UndoContents(Comdat.DOZP.Process.DozpService.ScanFileRequest request) {
            return base.Channel.UndoContents(request);
        }
        
        public Comdat.DOZP.Process.DozpService.ScanFileResponse DeleteScanFile(Comdat.DOZP.Process.DozpService.ScanFileRequest request) {
            return base.Channel.DeleteScanFile(request);
        }
        
        public bool LogError(string application, string machineName, string message) {
            return base.Channel.LogError(application, machineName, message);
        }
    }
}
